### PR TITLE
Use goreleaser to build and release

### PR DESCRIPTION
**Pull request by Itxaka**
Instead of using gox on one side and an action to release, we can merge
them together with goreleaser which will build for extra targets (arm,
mips if needed in the future) and it also takes care of creating
checksums, a source archive, and a changelog and creating a release with
all the artifacts.

All binaries should respect the old naming convention, so any scripts
out there should still work.

Signed-off-by: Itxaka <igarcia@suse.com>

### CODE REVIEW

**Comment by Itxaka** [comment]
oh yeah, test requirements for PRs have to be changed manually due to the name change, sorry about that :D

**Comment by mudler** [comment]
Looks good! let's see how it goes in the next rel :)

**Comment by Itxaka** [comment]
@mudler we could always create a fake release, delete it afterwards, to check that it's actually working as expected, so we don't get any failures when we do a real release

**Comment by mudler** [comment]
oh well, develop already fails with:

```
   ⨯ release failed after 8.98s error=failed to get module path: exit status 1: go: inconsistent vendoring in /home/runner/work/luet/luet:
	golang.org/x/oauth2@v0.0.0-20210810183815-faf39c7919d5: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	golang.org/x/text@v0.3.7: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	google.golang.org/genproto@v0.0.0-20210811021853-ddbe55d93216: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	golang.org/x/oauth2@v0.0.0-20210805134026-6f1e6394065a: is marked as explicit in vendor/modules.txt, but not explicitly required in go.mod
	google.golang.org/genproto@v0.0.0-20210809142519-0135a39c2737: is marked as explicit in vendor/modules.txt, but not explicitly required in go.mod

	To ignore the vendor directory, use -mod=readonly or -mod=mod.
	To sync the vendor directory, run:
		go mod vendor
```

**Pull request merged**
